### ISSUE TITLE
Error on an array view

### ISSUE THREAD

**Issue by gdalle** [tecosaur/About.jl#34] opened 2024-09-09 06:43 UTC
```julia
julia> about(view(zeros(10), 1:2))
2-element view(::Vector{Float64}, 1:2) with eltype Float64 (<: AbstractVector{Float64} <: Any), occupies 40B directly (referencing 160B in total, holding 16B of data)
ERROR: Type Array does not have a definite size.
Stacktrace:
  [1] sizeof(x::Type)
    @ Base ./essentials.jl:631
  [2] (::About.var"#11#12"{DataType})(i::Int64)
    @ About ~/.julia/packages/About/52iMk/src/types.jl:22
  [3] iterate
    @ ./generator.jl:47 [inlined]
  [4] _collect(c::UnitRange{Int64}, itr::Base.Generator{UnitRange{Int64}, About.var"#11#12"{DataType}}, ::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base ./array.jl:854
  [5] collect_similar
    @ ./array.jl:763 [inlined]
  [6] map
    @ ./abstractarray.jl:3285 [inlined]
  [7] structinfo
    @ ~/.julia/packages/About/52iMk/src/types.jl:13 [inlined]
  [8] memorylayout(io::Base.TTY, value::SubArray{Float64, 1, Vector{Float64}, Tuple{UnitRange{Int64}}, true})
    @ About ~/.julia/packages/About/52iMk/src/values.jl:63
  [9] about(io::Base.TTY, value::SubArray{Float64, 1, Vector{Float64}, Tuple{UnitRange{Int64}}, true})
    @ About ~/.julia/packages/About/52iMk/src/values.jl:43
 [10] about(x::SubArray{Float64, 1, Vector{Float64}, Tuple{UnitRange{Int64}}, true})
    @ About ~/.julia/packages/About/52iMk/src/About.jl:201
 [11] top-level scope
    @ REPL[9]:1
```

**Comment by tecosaur** [comment] 2024-10-18 12:45
I can't reproduce this on the development version, I suspect it may have been incidentally fixed by f232aaacdd9d97c31bd796c02a31a011ecedc26d.

**Closed** 2024-10-18 12:56 UTC
Labels: bug
